name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci --no-audit --no-fund --silent

      - name: Generate coverage results
        run: |
          COVERAGE=$(npm run --silent coverage:badge | tail -2 | head -1 | awk '{ print $3; }')

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 821e7285c63cfbd377febe05893e1046
          filename: onirim__main.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: github
